- name: installing nginx and run
  hosts: web
  tasks:
  - name: install nginx
    ansible.bultin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started