- name: variables
  hosts: web
  vars:
    person: ramesh
    wish: night
  tasks:
    - name: test varibles
      ansible.builtin.debug:
       msg: "bye {{person}}, good {{wish}}"
    
    - name: print info
      vars:
       person: ganesh
      ansible.builtin.debug:
       msg: "bye {{person}}, good {{wish}}"

    - name: print info again
      vars:
       person: mamatha
       wish: morning
      ansible.builtin.debug:
       msg: "Hi {{person}}, good {{wish}}"