- name: print the info
  hosts: web
  vars_prompt:
   - name: name
     prompt: please enter the name
   - name: age
     prompt: please enter the age
  tasks:
   - name: print the bio data
     ansible.builtin.debug:
      msg: "hi sir, my name is {{name}} and my age is {{age}}"